### ISSUE TITLE
Missing artifact labo.jim:xslt-quality:jar:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Guillaume789** [sonar-xsl/Sonar-XSL-Plugin#1]
Hi,
I have retrieved your code, however maven complain about missing artefact in project 'sonar-xsl-plugin': "Missing artifact labo.jim:xslt-quality:jar:0.0.1-SNAPSHOT"

I tried to search for this library on Google, but couldn't find it.
Could you please let me know which repository I should add in the pom.xml to fix this issue?

Thanks,
Guillaume

**Comment by Guillaume789** [comment]
I just noticed that this lib is part of your repositories. I have defined a local system path to fix the dependency issue.

**Comment by jimetevenard** [comment]
Hi @Guillaume789 , 

I'm getting back to work on this project these days.

Strange coincidence, I just read your message this afternoon, and I was just f**ixing this creepy build by merging all the repositories into a single [multi-module project](https://maven.apache.org/guides/mini/guide-multiple-modules.html)**. (See Issue #2)
I'll merge it in a few days, once tested on several maven versions/platforms.

So, all the sources will be here, in this repository , and the entire project will be built with a single `mvn install`.
Since the others repositories do not handle significant history or issues, they will be deleted.

It will be pretty much simple, I guess.
Regards
